### ISSUE TITLE
No internet connection

### ISSUE THREAD

**Issue by Amparose** [ritashugisha/Luxinate#4]
Recently I suddenly am getting "No internet connection" messages when trying to use Luxinate. This is happening on two different machines (10.10.3). I have reinstalled the workflow and ran the youtube update in the workflow; still no dice.

Any ideas?

**Comment by stephen-bunn** [comment]
Where did you download the workflow from? The AlfredForum or Packal?

**Comment by Amparose** [comment]
Can't remember where I downloaded it from originally but I updated by downloading from Packal. Neither installs (old and updated) work.

**Comment by stephen-bunn** [comment]
I've just reposted an updated version of the workflow to Packal. An older version was being hosted by Packal. Try re-downloading and re-installing, hopefully the updated post will fix your issue.

**Comment by Amparose** [comment]
Just downloaded and all works. Thanks for that! Awesome work btw!

**Comment by pirate** [comment]
How do I get the white icons back on the new version?

**Comment by pirate** [comment]
Nevermind, figured it out. I just renamed the -light icons in the workflow folder.
